### ISSUE TITLE
Working with near RAM-sized datasets

### ISSUE THREAD

**Issue by hombit** [lincc-frameworks/tape#221]
I'm trying to load [Plasticc](https://zenodo.org/record/2539456) dataset with `Ensemble.from_source_dict()` because of an out-of-memory issue.

Here I use a single light-curve ("source") file out of 11 test dataset files.

```python
import pandas as pd
from tape import Ensemble, ColumnMapper

object_table = pd.read_csv(
    "plasticc_test_metadata.csv.gz",
    index_col="object_id",
)
source_table = pd.read_csv(
    "plasticc_test_lightcurves_02.csv.gz",
    index_col="object_id"
)
source_table = source_table.merge(object_table, on="object_id")

ens = Ensemble()
ens.from_source_dict(
    source_table.to_dict(orient="series"),
    npartitions=10,
    column_mapper=ColumnMapper(
        id_col='object_id',
        time_col='mjd',
        flux_col='flux',
        err_col='flux_err',
        band_col='passband',
    ),
)
```

Traceback
```
/Users/hombit/.virtualenvs/tape/lib/python3.11/site-packages/distributed/client.py:3160: UserWarning: Sending large graph of size 9.94 GiB.
This may cause some slowdown.
Consider scattering data ahead of time and using futures.
  warnings.warn(
2023-09-05 11:42:46,648 - distributed.protocol.core - CRITICAL - Failed to Serialize
Traceback (most recent call last):
  File "/Users/hombit/.virtualenvs/tape/lib/python3.11/site-packages/distributed/protocol/core.py", line 109, in dumps
    frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hombit/.virtualenvs/tape/lib/python3.11/site-packages/msgpack/__init__.py", line 38, in packb
    return Packer(**kwargs).pack(o)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "msgpack/_packer.pyx", line 294, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 300, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 297, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 202, in msgpack._cmsgpack.Packer._pack
ValueError: bytes object is too larg
```

These 9.94 GiB is consistent with 10.2GB in `source_table.info()`.

I use current HEAD, macOS 13.5, Python 3.11.5, Dask 2023.8.1. I have 32 GB of RAM

What is the right way for working with large datasets? Do/should we provide a better way of loading a dataset having a lot of columns in the "object" table?

**Comment by hombit** [comment]
Thank you, @wilsonbb. I opened #223 with a proposal of a better load function. Feel free to close this one if you believe that implementing that would be enough to fix the "large" dataset problem

**Comment by wilsonbb** [comment]
I agree that this is probably in a state we can close due to progress on the eclipsing binaries notebook, with work for larger datasets tracked by the science drivers.. @hombit feel to re-open if you disagree
